name: modularity_cli
description: CLI tools for Modularity framework visualization.
version: 0.0.1
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/modularity_cli

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  modularity_contracts: ^0.0.1
  path: ^1.8.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
