name: modularity_cli
description: CLI tools for Modularity framework visualization.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  modularity_contracts:
    path: ../contracts
  path: ^1.8.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
