name: modularity_test
description: Testing utilities for Modularity framework.
version: 0.0.1
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/modularity_test

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  modularity_contracts: ^0.0.1
  modularity_core: ^0.0.1
  test: ^1.24.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^3.0.0
