name: example_auto_route
description: A complex example demonstrating AutoRoute integration with Modularity.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.0.0
  modularity_flutter:
    path: ../../packages/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^9.0.0



