name: complex_mobx
description: A complex E-Commerce example using Modularity, MobX, and Nested Modules.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  provider: ^6.0.0 # Useful for injecting Stores into Widget tree if needed, or we can use GetIt/Binder directly
  modularity_flutter:
    path: ../../packages/flutter
  modularity_core:
    path: ../../packages/core
  modularity_contracts:
    path: ../../packages/contracts

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  modularity_cli:
    path: ../../packages/modularity_cli

