name: modularity_core
description: Core logic for Modularity framework (Graph, Lifecycle, DI).
version: 0.0.1
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/core

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  modularity_contracts: ^0.0.1
  meta: ^1.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
