name: modularity_core
description: Core logic for Modularity framework (Graph, Lifecycle, DI).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  modularity_contracts:
    path: ../contracts
  meta: ^1.7.0

dev_dependencies:
  test: ^1.24.0
