name: modularity_flutter
description: Flutter integration for Modularity framework.
version: 0.0.1
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modularity_contracts: ^0.0.1
  modularity_core: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
