name: modularity_injectable_adapter
description: Injectable + GetIt integration utilities for the Modularity framework.
version: 0.0.1
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/modularity_injectable_adapter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  get_it: ^7.6.4
  injectable: ^2.3.2
  modularity_contracts: ^0.0.1
  modularity_core: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

