name: modularity_contracts
description: Zero-dependency interfaces for Modularity framework.
version: 0.0.1
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/contracts

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
