name: modularity_get_it
description: GetIt adapter for Modularity.
version: 0.0.1
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/adapters/modularity_get_it

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  get_it: ^8.0.0
  modularity_contracts: ^0.0.1

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
